apiVersion: v1
kind: Service
metadata:
  name: screenerService
  labels:
    app: screenerService
spec:
  type: LoadBalancer
  selector:
    app: screener
  ports:
    - port: 80
      targetPort: 8080