apiVersion: apps/v1
kind: Deployment
metadata:
  name: screenerDeployment
  labels:
    app: screener
spec: # ReplicaSet
  replicas: 1
  selector:
    matchLabels:
      app: screener
  template: # Pod
    metadata:
      labels:
        app: screener
    spec:
      containers:
        - name: screener
          image: screener:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
            requests:
              cpu: "150m"
              memory: "256Mi"

